# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='slug',
        ),
        migrations.AddField(
            model_name='snippet',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='stars',
            field=models.PositiveIntegerField(default=0, verbose_name='stars'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='used',
            field=models.PositiveIntegerField(default=0, verbose_name='used'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='version'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='visibility',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Unlisted'), (3, 'Private')], default=1, verbose_name='visibility'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.TextField(max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='name'),
        ),
    ]
