# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20160331_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last used'),
        ),
    ]
