# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 20:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='label')),
                ('fingerprint', models.CharField(max_length=255, verbose_name='fingerprint')),
                ('key', models.TextField(max_length=1000, verbose_name='key')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='added on')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='last used')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssh_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('label',),
                'db_table': 'ssh_keys',
                'verbose_name': 'ssh key',
                'verbose_name_plural': 'ssh keys',
            },
        ),
    ]
