# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold_templates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('extension', models.CharField(blank=True, max_length=10, null=True, verbose_name='extension')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='size')),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'folder',
                'verbose_name_plural': 'folders',
            },
        ),
        migrations.AlterModelOptions(
            name='scaffoldtemplate',
            options={'ordering': ('-updated_at',), 'verbose_name': 'scaffold template', 'verbose_name_plural': 'scaffold template'},
        ),
        migrations.AlterField(
            model_name='scaffoldtemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaffoldtemplates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='scaffoldtemplate',
            unique_together=set([('user', 'slug')]),
        ),
        migrations.AddField(
            model_name='folder',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='scaffold_templates.ScaffoldTemplate'),
        ),
        migrations.AddField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scaffold_templates.Folder'),
        ),
        migrations.AddField(
            model_name='file',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scaffold_templates.ScaffoldTemplate'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set([('template', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('template', 'name')]),
        ),
    ]
