# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold_templates', '0002_auto_20160404_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='size',
            field=models.PositiveIntegerField(default=0, verbose_name='size'),
        ),
    ]
