# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold_templates', '0003_folder_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='scaffold_templates.Folder'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('template', 'name', 'folder')]),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set([('template', 'name', 'folder')]),
        ),
    ]
