# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold_templates', '0004_auto_20160410_1504'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='folder',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='template',
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('name',), 'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'File'), (2, 'Folder')], default=1, verbose_name='file type'),
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scaffold_templates.File'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together=set([('template', 'folder', 'name')]),
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
