# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 20:43
from __future__ import unicode_literals

import cmdbox.scaffold_templates.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold_templates', '0005_auto_20160410_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-file_type', 'name'), 'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.AlterField(
            model_name='file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scaffold_templates.File', validators=[cmdbox.scaffold_templates.validators.validate_folder]),
        ),
    ]
