# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scaffold_templates', '0007_auto_20160418_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='content'),
        ),
    ]
